import os
from src.config import DATASET_TAG, run_suffix


def _make_run_dir(base, model_type, cfg, dataset=None, params=None):
    """Directory a run writes into: {base}/{dataset}/{model_type}/{split tag}{variant tag}.

    The default comes from DATASET_TAG, not DATASET, so a forecast-weather run lands in
    models/dom_fc/ instead of overwriting the baseline weights in models/dom/. An explicit
    `dataset` still wins — that is how the joint models reach models/joint_dom_bge/.

    The variant tag (_lds / _fds / _s2<mode>) is `run_suffix(params)` — the SAME function
    the config model_path strings use — so the directory a run WRITES and the path the
    evaluator/predictor READ are generated by one code path and cannot disagree.
    """
    tag = f"{cfg['split_strategy']}_test{cfg['test_frac']}"
    if 'val_strategy' in cfg:
        tag += f"_{cfg['val_strategy']}_val{cfg['val_frac']}"
    tag += run_suffix(params or {})
    path = os.path.join(base, dataset or DATASET_TAG, model_type, tag)
    os.makedirs(path, exist_ok=True)
    return path
